### ISSUE TITLE
OfflineDataset trace generation issue

### ISSUE THREAD

**Issue by saeidnp** [pyprob/pyprob#38]
When generating traces for offline dataset, it samples from the prior with `trace_mode=TraceMode.PRIOR` while it should be `TraceMode.PRIOR_FOR_INFERENCE_NETWORK`.
Here is the code line:
https://github.com/pyprob/pyprob/blob/c1127c362f83440644fb1a6dfc93f2f888f49a90/pyprob/nn/dataset.py#L132

**Comment by gbaydin** [comment]
Thank you @saeidnp for noticing this. I just pushed a commit fixing this.
